### ISSUE TITLE
Ajout

### ISSUE THREAD

**Issue by LorenzoMerguez** [camilleeyries/Acteur..js-agario-client-aimbot#1]
Ajoute moi skype : loloolo--
Je suis français.
Merci.
C'est assez important !!

**Comment by camilleeyries** [comment]
Je fait une petite "pause" pour le moment. Problèmes personnels...
Bonne nuit.

**Comment by LorenzoMerguez** [comment]
Ah, ok mais ce n'est pas possible de m'ajouter pour rester en contact ?
